### PR TITLE
Add og generator

### PR DESCRIPTION
**Pull request by KarimAED**
Feature: added og image generator

- Automatic generation of og images for documentation
- integration into travis CI
- updated readme

### CODE REVIEW

**Comment by KarimAED** [comment]
I agree with the CLA.

**Comment by bobvanluijt** [comment]
Hi @KarimAED –

Thanks! A few questions:

- Can you please rename the dir `Python` to `_python`.
- Can you please keep it to 1 job instead of two? You can simply install Python (if this is an issue I can do this too)

**Comment by bobvanluijt** [comment]
Conceptually all looks good. Probably you need [here](https://github.com/KarimAED/weaviate-io/blob/add-og-generator/.travis.yml#L9) to use `python3-pip` because it's [focal](https://github.com/KarimAED/weaviate-io/blob/add-og-generator/.travis.yml#L2)

**Comment by bobvanluijt** [comment]
@KarimAED – great. We are almost there.

Question, how do you currently determine the text in the image? Ideally, we remove all the `og: ` in the headers and automatically determine this in this header file.

**Comment by KarimAED** [comment]
@bobvanluijt Thanks, yea the changes took me a second because my ide was acting up a little (with refactoring etc.)

The images use the `sub-menu:` and `title:` tags for their text. The `og:` tag is currently only used to pass the location of the image file, but that could also be determined programmatically, as there is a fixed naming scheme (as outlined in the added readme section). I'm not quite sure what you mean by the header file? If you point me towards a more programmatic approach, I can also implement that.

**Comment by bobvanluijt** [comment]
Hi @KarimAED –

The og images are selected here: `https://github.com/semi-technologies/weaviate-io/blob/main/_includes/head.html#L34-L41`

What you could do for the documentation is remove all the `og: ` references in the individual documentation docs. And simply determine what the right path is [here](https://github.com/semi-technologies/weaviate-io/blob/main/_includes/head.html#L37-L38).

**Comment by KarimAED** [comment]
@bobvanluijt Cheers! I set something up, but I'm definitely not a Liquid expert, so you might want to double check if everything makes sense.

**Pull request merged**
