### PR TITLE
added images for previews

### PR DESCRIPTION
**Pull request by dvanderrijst**
Hi Etienne, 
I have added all images for previews. 
Also, have I adjusted the settings in each markdown file, where I changed `og-img:`

@etiennedi The only thing that needs to be adjusted is [this document,](https://github.com/semi-technologies/weaviate-io/blob/main/_includes/head.html) wherein line 34 the settings for which preview image is chosen can be found. Can you merge this branch with `main` and do the last edits?

### CODE REVIEW

**Comment by bobvanluijt** [comment]
@etiennedi – do you want me to do this? I can relatively easy do it

**Review by bobvanluijt — CHANGES_REQUESTED** [review]
@dvanderrijst – OG images must be `1200×630 pixels` that's currently not the case.

**Comment by dvanderrijst** [comment]
@bobvanluijt I'll update the image sizes

**Comment by bobvanluijt** [comment]
Thanks @dvanderrijst

**Review by bobvanluijt — APPROVED** [review]

**Pull request merged**
